#!/usr/bin/env bash
# Bash script to install and configure HAProxy load balancer

sudo apt install -y software-properties-common
sudo apt-get -y update
sudo apt-get install -y haproxy

# Install HAProxy
sudo apt install -y haproxy=1.8.\*

hgproxy_conf_file="/etc/haproxy/haproxy.cfg"

# Configure Load Balancer
fname="frontend http"
fbind="bind *:80"
fmode="mode http"
fdefault="default_backend web-backend"
frontend="$fname\n\t$fbind\n\t$fmode\n\t$fdefault\n"

bname="backend web-backend"
bbalance="balance roundrobin"
bserver1="server web1 3.80.18.115:80 check"
bserver2="server web2 3.90.65.239:80 check"
backend="$bname\n\t$bbalance\n\t$bserver1\n\t$bserver2"

sudo sed -i "$ a $frontend" $hgproxy_conf_file
sudo sed -i "$ a $backend" $hgproxy_conf_file

# Restart HAProxy
sudo service haproxy restart
