#!/usr/bin/env bash
# Bash script to configure the nginx server for connection on port 80
sudo sed -i 's/8080 default_server/80 default_server/g' /etc/nginx/sites-enabled/default
sudo service nginx restart
