#!/usr/bin/env bash
# This script prints Fizzbuzz, Fizz or Buzz

count=1

while [ $count -lt "21" ]
do
  if [ $((count % 3)) == 0 ] && [ $((count % 5)) == 0 ]
  then
    echo "Fizzbuzz"

elif [ $((count % 3)) == 0 ]
  then
    echo "Fizz"

elif [ $((count % 5)) == 0 ]
  then
    echo "Buzz"

  else
    echo $count
  fi
  (( count++ ))
done
